# Generated by Django 5.2.4 on 2025-07-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('Com', 'Compresora'), ('Mot', 'Motor'), ('Bom', 'Bomba'), ('Gen', 'Generador'), ('Otr', 'Otro')], default='Otr', max_length=3),
        ),
    ]
