# Generated by Django 5.2.4 on 2025-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_numero_serie_equipo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='garantia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
