# Generated by Django 5.2.4 on 2025-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_area_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(help_text='Tipo de equipo (ej: Compresora, Motor, etc.)', max_length=50),
        ),
    ]
