# Generated by Django 5.2.4 on 2025-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_equipo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='equipo',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el equipo', verbose_name='Observación'),
        ),
    ]
