# Generated by Django 5.2.4 on 2025-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_sede_equipo_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_mantenimiento',
            field=models.DateField(blank=True, help_text='Fecha del próximo mantenimiento programado', null=True, verbose_name='Fecha de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='vida_util',
            field=models.IntegerField(blank=True, help_text='Vida útil estimada del equipo en años', null=True, verbose_name='Vida Útil (años)'),
        ),
    ]
