# Generated by Django 5.2.4 on 2025-08-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_equipo_fecha_mantenimiento_equipo_vida_util'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('puede_eliminar', models.BooleanField(default=False, verbose_name='Puede eliminar equipos')),
                ('puede_editar', models.BooleanField(default=True, verbose_name='Puede editar equipos')),
                ('puede_crear', models.BooleanField(default=True, verbose_name='Puede crear equipos')),
                ('puede_exportar', models.BooleanField(default=True, verbose_name='Puede exportar datos')),
                ('puede_importar', models.BooleanField(default=False, verbose_name='Puede importar datos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
