services:
  - type: web
    name: inventario-activos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn inventario_activos.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inventario-activos-db
          property: connectionString

databases:
  - name: inventario-activos-db
    databaseName: inventario_activos
    user: inventario_user
    plan: free 